#!/bin/bash

SAN_MARINO_BLUE=0xff1e3a5f
CORAL_ACCENT=0xff64b5f6
INACTIVE_BLUE=0xff3d5a7a

options=(
  style=round
  width=3.0
  hidpi=on
  active_color=$CORAL_ACCENT
  inactive_color=$INACTIVE_BLUE
)

borders "${options[@]}"
