tap "FelixKratz/formulae"
tap "nikitabobko/tap"

brew "fzf"
brew "go"
brew "git-delta"
brew "jq"
brew "lsd"
brew "lua"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "node"
brew "ripgrep"
brew "borders"
brew "sketchybar"
brew "stow"
brew "zellij"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "aerospace"
cask "font-fira-code-nerd-font"
