#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonightStorm"

ACTIVE_APP_LABEL_COLOR="$highlight_color"
ACTIVE_APP_BACKGROUND_BORDER_COLOR="$accent_color"

sketchybar --add item active_app_spacer_left left \
           --set      active_app_spacer_left \
                      background.drawing=off

sketchybar --add item  active_app left \
           --subscribe active_app front_app_switched \
           --set       active_app \
                       background.drawing=off \
                       label.color="$LABEL_COLOR" \
                       label.padding_left=10 \
                       label.padding_right=10 \
                       script="$PLUGIN_DIR/active_app"

sketchybar --add item active_app_spacer_right left \
           --set      active_app_spacer_right \
                      background.drawing=off

sketchybar --add bracket active_app_bracket active_app_spacer_left active_app active_app_spacer_right \
           --set         active_app_bracket \
                         background.border_color="$BACKGROUND_BORDER_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
