#!/bin/bash

# SPACE_SIDS=($(aerospace list-workspaces --all));
# for sid in $(aerospace list-workspaces --all); do
#   sketchybar --add item space.$sid left \
#     --subscribe space.$sid aerospace_workspace_change \
#     --set space.$sid \
#     background.color=0x44ffffff \
#     background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS"  \
#     background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH" \
#     background.height=20 \
#     background.drawing=off \
#     label="$sid" \
#     label.padding_right=4 \
#     label.padding_left=4 \
#     background.padding_left=2 \
#     background.padding_right=2 \
#     label.align=center \
#     click_script="aerospace workspace $sid" \
#     script="$CONFIG_DIR/plugins/aerospace.sh $sid" \
#     background.border_color="$FRONT_APP_BACKGROUND_BORDER_COLOR" \
#
#     background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
#
#
#   done
# for sid in "${SPACE_SIDS[@]}"
#
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color="0x44ffffff" \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=on \
        label="$sid" \
        label.padding_right=20                     \
        label.y_offset=-1    \
        label.color=$WHITE \
        # background.color=$BAR_COLOR \

        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
        # script="$PLUGIN_DIR/space.sh"

done

# for sid in $(aerospace list-workspaces --all); do
#   sketchybar --add item space.$sid left                                 \
#     --subscribe space.$sid aerospace_workspace_change \
#     --set space.$sid space=$sid                                 \
#     label="$sid" \
#     label.padding_right=4 \
#     label.padding_left=4 \
#     background.padding_left=2 \
#     background.padding_right=2 \
#     label.color=$ACCENT_COLOR \
#     icon.color=$ACCENT_COLOR \
#     label.font="Hack Nerd Font:Bold:14.0" \
#     background.drawing=off \
#     click_script="aerospace workspace $sid" \
#     script="$CONFIG_DIR/plugins/aerospace.sh $sid" \
#     # label.padding_right=20                     \
#     # label.y_offset=-1                          \
#     script="$PLUGIN_DIR/space.sh"
# done
#
# sketchybar --add item space_separator left                             \
#            --set space_separator icon="􀆊"                                \
#                                  icon.color=$ACCENT_COLOR \
#                                  icon.padding_left=4                   \
#                                  label.drawing=off                     \
#                                  background.drawing=off                \
#                                  script="$PLUGIN_DIR/space_windows.sh" \
#            --subscribe space_separator space_windows_change
