#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonightStorm"

if [ "$SENDER" = "aerospace_service_mode_enabled_changed" ]; then
  if [ "$AEROSPACE_SERVICE_MODE_ENABLED" = true ]; then
    sketchybar --set workspaces_service_mode \
                     label.drawing=on \
                     label.highlight=on \
                     label='Service'
                     # background.color="0x44ffffff"\

  else
    sketchybar --set workspaces_service_mode \
                     label.drawing=on \
                     label.highlight=off \
                     label.color="$label_color" \
                     label='Norm'
                     # background.color="0x44ffffff"\

  fi
fi

if [ "$SENDER" = "aerospace_workspace_change" ]; then
  if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME \
                     label.highlight=on \
                     background.color="$bracket_bg_highlight" \
                     label.color="$label_color_highlight" \
                     background.drawing=on
                     # label.font="$LABEL_HIGHLIGHT_FONT"\

  else
    sketchybar --set $NAME \
                     label.highlight=off \
                     background.color="$bracket_bg" \
                     label.color="$label_color"\
                     background.drawing=off

                     # label.font="$LABEL_FONT" \
  fi
fi

#!/usr/bin/env bash

# source "$CONFIG_DIR/environment"
# source "$CONFIG_DIR/colors.sh"
# source "$THEME_DIR/tokyonight"
#
# if [ "$SENDER" = "aerospace_service_mode_enabled_changed" ]; then
#   if [ "$AEROSPACE_SERVICE_MODE_ENABLED" = true ]; then
#     sketchybar --set workspaces_service_mode \
#                      label.drawing=on
#   else
#     sketchybar --set workspaces_service_mode \
#                      label.drawing=off
#   fi
# fi
#
# if [ "$SENDER" = "aerospace_workspace_change" ]; then
# if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
#   sketchybar --set $NAME \
#     label.highlight=on \
#     label.drawing=on \
#
#     # label.font="$LABEL_HIGHLIGHT_FONT"\
#   label.color=$ACCENT_COLOR
#   # label.color=$ACCENT_COLOR
# else
#   sketchybar --set $NAME \
#     label.highlight=off \
#     label.color=$ITEM_BG_COLOR
#   # label.font="$LABEL_FONT"
# fi
# fi

