#!/usr/bin/env bash

# PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonightStorm"

# Configure general bar appearance.
bar=(
    blur_radius="$BAR_BLUR_RADIUS"
    # border_color="$BAR_BORDER_COLOR"
    border_color="$bracket_border"
    # color="$BAR_COLOR"
    color="$bar_color"
    corner_radius="$BAR_CORNER_RADIUS"
    height="$BAR_HEIGHT"
    margin="$BAR_MARGIN"
    position="$BAR_POSITION"
    padding_left="$BAR_PADDING"
    padding_right="$BAR_PADDING"
    y_offset="$BAR_Y_OFFSET"
)
sketchybar --bar "${bar[@]}"

# Configure default values for later defined items.
default=(
  # background.color="$BACKGROUND_COLOR"
  background.color="$bracket_bg"
  # background.border_color="$BACKGROUND_BORDER_COLOR"
  background.border_color="$bracket_border"
  background.corner_radius="$BACKGROUND_CORNER_RADIUS"
  background.height="$BACKGROUND_HEIGHT"
  background.drawing=on
  icon.drawing=on
  icon.font="$ICON_FONT"
  label.align="$LABEL_ALIGN"
  label.font="$LABEL_FONT"
  # label.color="$LABEL_COLOR"
  label.color="$label_color"
  # label.highlight_color="$LABEL_HIGHLIGHT_COLOR"
  label.highlight_color="$label_color_highlight"
  label.y_offset="$LABEL_Y_OFFSET"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
  background.height="$LABEL_MARGIN"
  y_offset="$Y_OFFSET"
)
sketchybar --default "${default[@]}"

# Left


source "$ITEM_DIR/aerospace"
# source "$ITEM_DIR/spacer"
# source "$ITEM_DIR/front_app"

source "$ITEM_DIR/spacer"
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=on background.drawing=off
           # --add item front_app left \
           # --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           # --subscribe front_app front_app_switched

source "$ITEM_DIR/front_app"

# source "$ITEM_DIR/spacer"
# source "$ITEM_DIR/active_app"
# Right
source "$ITEM_DIR/clock"

source "$ITEM_DIR/right_spacer"
sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

# Automatically apply configuration changes
sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
