# General settings
set -g default-terminal "screen-256color"  # Set terminal type for 256-color support
set -g mouse on  # Enable mouse support
set -g status-position top  # Move status bar to the top
set-option -g status-justify centre  # Center-align status bar content

# set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1

# Reload config
unbind r  # Unbind default 'r' key
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded...:) "

# Copy pasting
bind -T copy-mode-vi v send -X begin-selection # highlight
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy" # yank
bind P paste-buffer # paste
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel # system clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy" # copy on highlight

# Vim-like keybindings for pane navigation
setw -g mode-keys vi  # Use vi mode for copy mode
bind -r ^ last-window  # Switch to the last window
bind-key h select-pane -L  # Move to the left pane
bind-key j select-pane -D  # Move to the bottom pane
bind-key k select-pane -U  # Move to the top pane
bind-key l select-pane -R  # Move to the right pane

# Pane resizing
# unbind C-Left
# unbind C-Right
# unbind C-Up
# unbind C-Down
# bind -r C-Left resize-pane -L 5
# bind -r C-Right resize-pane -R 5
# bind -r C-Up resize-pane -U 5
# bind -r C-Down resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind-key + resize-pane -D 10  # Resize pane down by 10 rows
bind-key - resize-pane -U 10  # Resize pane up by 10 rows
bind-key t split-window -v -l 25%  # Create a small horizontal split (25% height)

# Window and session navigation
bind-key b last-window  # Toggle to the last window
bind -n M-P switch-client -p  # Move to the previous session (Alt+P)
bind -n M-N switch-client -n  # Move to the next session (Alt+N)
bind ` switch-client -l  # Switch to the last session

# Pane border settings
set -g pane-border-lines single  # Use single-line pane borders
set -g pane-border-style fg=default,bg=default  # Border style for inactive panes
set -g pane-active-border-style fg=blue,bg=default  # Border style for active panes
set -g pane-border-format "#{pane_index} #{pane_current_command} #{pane_current_path}"  # Pane border format

