#!/usr/bin/env bash

echo "SIMPLE TEST SCRIPT"
echo "=================="
echo "If you can see this, the popup works"
echo ""
echo "Press any key to continue..."
read -n 1
echo ""
echo "Test completed!"